vim.cmd('highlight clear')

if vim.fn.exists('syntax_on') == 1 then
    vim.cmd('syntax reset')
end

vim.o.background = 'dark'
vim.g.colors_name = 'ghostty-default'

local c = {
    bg = '#282c34',
    bg_dark = '#1d1f21',
    bg_highlight = '#353a44',
    fg = '#ffffff',
    fg_dim = '#c5c8c6',
    black = '#1d1f21',
    red = '#cc6666',
    green = '#b5bd68',
    yellow = '#f0c674',
    blue = '#81a2be',
    magenta = '#b294bb',
    cyan = '#8abeb7',
    white = '#c5c8c6',
    bright_black = '#666666',
    bright_red = '#d54e53',
    bright_green = '#b9ca4a',
    bright_yellow = '#e7c547',
    bright_blue = '#7aa6da',
    bright_magenta = '#c397d8',
    bright_cyan = '#70c0b1',
    bright_white = '#eaeaea',
    search = '#ffe082',
    search_selected = '#f2a57e',
    none = 'NONE',
}

local terminal_colors = {
    c.black,
    c.red,
    c.green,
    c.yellow,
    c.blue,
    c.magenta,
    c.cyan,
    c.white,
    c.bright_black,
    c.bright_red,
    c.bright_green,
    c.bright_yellow,
    c.bright_blue,
    c.bright_magenta,
    c.bright_cyan,
    c.bright_white,
}

for index, color in ipairs(terminal_colors) do
    vim.g['terminal_color_' .. (index - 1)] = color
end

local function hi(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

local groups = {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg_dim, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_dark },
    FloatBorder = { fg = c.bright_black, bg = c.bg_dark },
    FloatTitle = { fg = c.bright_blue, bg = c.bg_dark, bold = true },
    ColorColumn = { bg = c.bg_highlight },
    Cursor = { fg = c.bg_highlight, bg = c.fg },
    CursorLine = { bg = c.bg_highlight },
    CursorColumn = { bg = c.bg_highlight },
    CursorLineNr = { fg = c.yellow, bg = c.bg_highlight, bold = true },
    LineNr = { fg = c.bright_black },
    LineNrAbove = { fg = c.bright_black },
    LineNrBelow = { fg = c.bright_black },
    SignColumn = { bg = c.bg },
    FoldColumn = { fg = c.bright_black, bg = c.bg },
    Folded = { fg = c.fg_dim, bg = c.bg_highlight },
    EndOfBuffer = { fg = c.bg },
    Conceal = { fg = c.bright_blue },
    Directory = { fg = c.blue, bold = true },
    WinSeparator = { fg = c.bright_black },
    VertSplit = { fg = c.bright_black },
    StatusLine = { fg = c.bright_white, bg = c.bg_highlight },
    StatusLineNC = { fg = c.fg_dim, bg = c.bg_dark },
    WinBar = { fg = c.bright_white, bg = c.bg },
    WinBarNC = { fg = c.fg_dim, bg = c.bg },
    TabLine = { fg = c.fg_dim, bg = c.bg_dark },
    TabLineFill = { bg = c.bg_dark },
    TabLineSel = { fg = c.fg, bg = c.bg_highlight, bold = true },
    Visual = { fg = c.bg, bg = c.fg },
    VisualNOS = { fg = c.bg, bg = c.fg_dim },
    Search = { fg = '#000000', bg = c.search },
    IncSearch = { fg = '#000000', bg = c.search_selected },
    CurSearch = { fg = '#000000', bg = c.search_selected },
    Substitute = { fg = '#000000', bg = c.bright_yellow },
    MatchParen = { fg = c.bright_yellow, bg = c.bg_highlight, bold = true },
    Pmenu = { fg = c.fg, bg = c.bg_dark },
    PmenuSel = { fg = c.bg, bg = c.blue },
    PmenuKind = { fg = c.cyan, bg = c.bg_dark },
    PmenuKindSel = { fg = c.bg, bg = c.cyan },
    PmenuExtra = { fg = c.fg_dim, bg = c.bg_dark },
    PmenuExtraSel = { fg = c.bg, bg = c.fg_dim },
    PmenuSbar = { bg = c.bg_highlight },
    PmenuThumb = { bg = c.bright_black },
    WildMenu = { fg = c.bg, bg = c.yellow },
    Question = { fg = c.green },
    MoreMsg = { fg = c.green },
    ModeMsg = { fg = c.bright_blue },
    MsgArea = { fg = c.fg, bg = c.bg },
    MsgSeparator = { fg = c.bright_black, bg = c.bg },
    ErrorMsg = { fg = c.bright_red },
    WarningMsg = { fg = c.bright_yellow },
    Title = { fg = c.blue, bold = true },
    NonText = { fg = c.bright_black },
    SpecialKey = { fg = c.bright_black },
    Whitespace = { fg = c.bg_highlight },
    DiffAdd = { fg = c.green, bg = c.bg_dark },
    DiffChange = { fg = c.yellow, bg = c.bg_dark },
    DiffDelete = { fg = c.red, bg = c.bg_dark },
    DiffText = { fg = c.bright_yellow, bg = c.bg_highlight, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.yellow },
    Removed = { fg = c.red },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.blue, undercurl = true },
    SpellLocal = { sp = c.cyan, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },

    Comment = { fg = c.bright_black, italic = true },
    Constant = { fg = c.yellow },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.yellow },
    Boolean = { fg = c.yellow },
    Float = { fg = c.yellow },
    Identifier = { fg = c.fg },
    Function = { fg = c.blue },
    Statement = { fg = c.magenta },
    Conditional = { fg = c.magenta },
    Repeat = { fg = c.magenta },
    Label = { fg = c.magenta },
    Operator = { fg = c.cyan },
    Keyword = { fg = c.magenta },
    Exception = { fg = c.magenta },
    PreProc = { fg = c.cyan },
    Include = { fg = c.magenta },
    Define = { fg = c.magenta },
    Macro = { fg = c.cyan },
    PreCondit = { fg = c.cyan },
    Type = { fg = c.yellow },
    StorageClass = { fg = c.magenta },
    Structure = { fg = c.yellow },
    Typedef = { fg = c.yellow },
    Special = { fg = c.cyan },
    SpecialChar = { fg = c.bright_cyan },
    Tag = { fg = c.blue },
    Delimiter = { fg = c.fg_dim },
    SpecialComment = { fg = c.bright_black, italic = true },
    Debug = { fg = c.red },
    Underlined = { fg = c.blue, underline = true },
    Ignore = { fg = c.bright_black },
    Error = { fg = c.bright_red },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    DiagnosticError = { fg = c.bright_red },
    DiagnosticWarn = { fg = c.bright_yellow },
    DiagnosticInfo = { fg = c.bright_blue },
    DiagnosticHint = { fg = c.bright_cyan },
    DiagnosticOk = { fg = c.bright_green },
    DiagnosticSignError = { fg = c.bright_red, bg = c.bg },
    DiagnosticSignWarn = { fg = c.bright_yellow, bg = c.bg },
    DiagnosticSignInfo = { fg = c.bright_blue, bg = c.bg },
    DiagnosticSignHint = { fg = c.bright_cyan, bg = c.bg },
    DiagnosticSignOk = { fg = c.bright_green, bg = c.bg },
    DiagnosticVirtualTextError = { fg = c.bright_red, bg = c.bg_dark },
    DiagnosticVirtualTextWarn = { fg = c.bright_yellow, bg = c.bg_dark },
    DiagnosticVirtualTextInfo = { fg = c.bright_blue, bg = c.bg_dark },
    DiagnosticVirtualTextHint = { fg = c.bright_cyan, bg = c.bg_dark },
    DiagnosticVirtualTextOk = { fg = c.bright_green, bg = c.bg_dark },
    DiagnosticUnderlineError = { sp = c.bright_red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.bright_yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.bright_blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.bright_cyan, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.bright_green, undercurl = true },
    LspReferenceText = { bg = c.bg_highlight },
    LspReferenceRead = { bg = c.bg_highlight },
    LspReferenceWrite = { bg = c.bg_highlight },

    TelescopeNormal = { fg = c.fg, bg = c.bg_dark },
    TelescopeBorder = { fg = c.bright_black, bg = c.bg_dark },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_highlight },
    TelescopePromptBorder = { fg = c.bg_highlight, bg = c.bg_highlight },
    TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
    TelescopePreviewTitle = { fg = c.bg, bg = c.green, bold = true },
    TelescopeResultsTitle = { fg = c.bg, bg = c.magenta, bold = true },
    TelescopeSelection = { fg = c.fg, bg = c.bg_highlight },
    TelescopeSelectionCaret = { fg = c.yellow, bg = c.bg_highlight },
    TelescopeMatching = { fg = c.bright_yellow, bold = true },

    MiniStatuslineModeNormal = { fg = c.bg, bg = c.blue, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg, bg = c.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineModeOther = { fg = c.bg, bg = c.cyan, bold = true },
    MiniStatuslineDevinfo = { fg = c.fg_dim, bg = c.bg_highlight },
    MiniStatuslineFileinfo = { fg = c.fg_dim, bg = c.bg_highlight },
    MiniStatuslineFilename = { fg = c.fg, bg = c.bg_dark },
    MiniStatuslineInactive = { fg = c.bright_black, bg = c.bg_dark },
    MiniDiffSignAdd = { fg = c.green, bg = c.bg },
    MiniDiffSignChange = { fg = c.yellow, bg = c.bg },
    MiniDiffSignDelete = { fg = c.red, bg = c.bg },
    MiniPickNormal = { fg = c.fg, bg = c.bg_dark },
    MiniPickBorder = { fg = c.bright_black, bg = c.bg_dark },
    MiniPickPrompt = { fg = c.bright_blue, bg = c.bg_dark },
    MiniPickMatchCurrent = { fg = c.bright_yellow, bg = c.bg_highlight, bold = true },

    BufferLineFill = { bg = c.bg_dark },
    BufferLineBackground = { fg = c.fg_dim, bg = c.bg_dark },
    BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineIndicatorSelected = { fg = c.blue, bg = c.bg },
    BufferLineSeparator = { fg = c.bg_dark, bg = c.bg_dark },
    BufferLineSeparatorSelected = { fg = c.bg_dark, bg = c.bg },
    BufferLineModified = { fg = c.yellow, bg = c.bg_dark },
    BufferLineModifiedSelected = { fg = c.bright_yellow, bg = c.bg },
    BufferLineCloseButton = { fg = c.bright_black, bg = c.bg_dark },
    BufferLineCloseButtonSelected = { fg = c.red, bg = c.bg },

    SnacksPicker = { fg = c.fg, bg = c.bg_dark },
    SnacksPickerBorder = { fg = c.bright_black, bg = c.bg_dark },
    SnacksPickerInput = { fg = c.fg, bg = c.bg_highlight },
    SnacksPickerMatch = { fg = c.bright_yellow, bold = true },
    SnacksPickerSelected = { fg = c.bright_blue, bg = c.bg_highlight },

    OilDir = { fg = c.blue, bold = true },
    OilDirIcon = { fg = c.blue },
    OilLink = { fg = c.cyan },
    OilSocket = { fg = c.magenta },
    OilOrphanLink = { fg = c.red },
    OilFile = { fg = c.fg },
    OilCreate = { fg = c.green },
    OilDelete = { fg = c.red },
    OilMove = { fg = c.yellow },
    OilCopy = { fg = c.cyan },

    TodoBgTODO = { fg = c.bg, bg = c.blue, bold = true },
    TodoBgFIX = { fg = c.bg, bg = c.red, bold = true },
    TodoBgWARN = { fg = c.bg, bg = c.yellow, bold = true },
    TodoBgNOTE = { fg = c.bg, bg = c.cyan, bold = true },
    TodoFgTODO = { fg = c.blue },
    TodoFgFIX = { fg = c.red },
    TodoFgWARN = { fg = c.yellow },
    TodoFgNOTE = { fg = c.cyan },
}

for group, opts in pairs(groups) do
    hi(group, opts)
end

local links = {
    ['@annotation'] = 'PreProc',
    ['@attribute'] = 'PreProc',
    ['@attribute.builtin'] = 'PreProc',
    ['@boolean'] = 'Boolean',
    ['@character'] = 'Character',
    ['@character.special'] = 'SpecialChar',
    ['@comment'] = 'Comment',
    ['@comment.documentation'] = 'Comment',
    ['@comment.error'] = 'DiagnosticError',
    ['@comment.note'] = 'DiagnosticInfo',
    ['@comment.todo'] = 'Todo',
    ['@comment.warning'] = 'DiagnosticWarn',
    ['@conditional'] = 'Conditional',
    ['@constant'] = 'Constant',
    ['@constant.builtin'] = 'Constant',
    ['@constant.macro'] = 'Macro',
    ['@constructor'] = 'Type',
    ['@debug'] = 'Debug',
    ['@define'] = 'Define',
    ['@exception'] = 'Exception',
    ['@field'] = 'Identifier',
    ['@float'] = 'Float',
    ['@function'] = 'Function',
    ['@function.builtin'] = 'Special',
    ['@function.call'] = 'Function',
    ['@function.macro'] = 'Macro',
    ['@include'] = 'Include',
    ['@keyword'] = 'Keyword',
    ['@keyword.conditional'] = 'Conditional',
    ['@keyword.conditional.ternary'] = 'Conditional',
    ['@keyword.coroutine'] = 'Keyword',
    ['@keyword.debug'] = 'Debug',
    ['@keyword.directive'] = 'PreProc',
    ['@keyword.directive.define'] = 'Define',
    ['@keyword.exception'] = 'Exception',
    ['@keyword.function'] = 'Keyword',
    ['@keyword.import'] = 'Include',
    ['@keyword.modifier'] = 'StorageClass',
    ['@keyword.operator'] = 'Operator',
    ['@keyword.repeat'] = 'Repeat',
    ['@keyword.return'] = 'Keyword',
    ['@keyword.type'] = 'Type',
    ['@label'] = 'Label',
    ['@markup.heading'] = 'Title',
    ['@markup.italic'] = 'Italic',
    ['@markup.link'] = 'Identifier',
    ['@markup.link.label'] = 'Identifier',
    ['@markup.link.url'] = 'Underlined',
    ['@markup.list'] = 'Delimiter',
    ['@markup.list.checked'] = 'DiagnosticOk',
    ['@markup.list.unchecked'] = 'DiagnosticHint',
    ['@markup.math'] = 'Special',
    ['@markup.quote'] = 'Comment',
    ['@markup.raw'] = 'String',
    ['@markup.strikethrough'] = 'Strikethrough',
    ['@markup.strong'] = 'Bold',
    ['@markup.underline'] = 'Underlined',
    ['@method'] = 'Function',
    ['@method.call'] = 'Function',
    ['@module'] = 'Include',
    ['@module.builtin'] = 'Include',
    ['@namespace'] = 'Include',
    ['@number'] = 'Number',
    ['@number.float'] = 'Float',
    ['@operator'] = 'Operator',
    ['@parameter'] = 'Identifier',
    ['@property'] = 'Identifier',
    ['@punctuation.bracket'] = 'Delimiter',
    ['@punctuation.delimiter'] = 'Delimiter',
    ['@punctuation.special'] = 'Special',
    ['@repeat'] = 'Repeat',
    ['@string'] = 'String',
    ['@string.documentation'] = 'String',
    ['@string.escape'] = 'SpecialChar',
    ['@string.regexp'] = 'SpecialChar',
    ['@string.regex'] = 'SpecialChar',
    ['@string.special'] = 'SpecialChar',
    ['@string.special.path'] = 'Underlined',
    ['@string.special.symbol'] = 'Identifier',
    ['@string.special.url'] = 'Underlined',
    ['@symbol'] = 'Identifier',
    ['@tag'] = 'Tag',
    ['@tag.attribute'] = 'Identifier',
    ['@tag.builtin'] = 'Tag',
    ['@tag.delimiter'] = 'Delimiter',
    ['@text'] = 'Normal',
    ['@text.danger'] = 'DiagnosticError',
    ['@text.emphasis'] = 'Italic',
    ['@text.environment'] = 'Macro',
    ['@text.environment.name'] = 'Type',
    ['@text.literal'] = 'String',
    ['@text.note'] = 'DiagnosticInfo',
    ['@text.reference'] = 'Identifier',
    ['@text.strike'] = 'Strikethrough',
    ['@text.strong'] = 'Bold',
    ['@text.title'] = 'Title',
    ['@text.todo'] = 'Todo',
    ['@text.underline'] = 'Underlined',
    ['@text.uri'] = 'Underlined',
    ['@text.warning'] = 'DiagnosticWarn',
    ['@type'] = 'Type',
    ['@type.builtin'] = 'Type',
    ['@type.definition'] = 'Typedef',
    ['@variable'] = 'Identifier',
    ['@variable.builtin'] = 'Special',
    ['@variable.member'] = 'Identifier',
    ['@variable.parameter'] = 'Identifier',
    ['@variable.parameter.builtin'] = 'Special',
    ['@diff.delta'] = 'Changed',
    ['@diff.minus'] = 'Removed',
    ['@diff.plus'] = 'Added',
    ['@function.method'] = 'Function',
    ['@function.method.call'] = 'Function',
    ['@lsp.type.class'] = 'Type',
    ['@lsp.type.enum'] = 'Type',
    ['@lsp.type.enumMember'] = 'Constant',
    ['@lsp.type.event'] = 'Type',
    ['@lsp.type.function'] = 'Function',
    ['@lsp.type.interface'] = 'Type',
    ['@lsp.type.keyword'] = 'Keyword',
    ['@lsp.type.macro'] = 'Macro',
    ['@lsp.type.method'] = 'Function',
    ['@lsp.type.namespace'] = 'Include',
    ['@lsp.type.number'] = 'Number',
    ['@lsp.type.operator'] = 'Operator',
    ['@lsp.type.parameter'] = 'Identifier',
    ['@lsp.type.property'] = 'Identifier',
    ['@lsp.type.string'] = 'String',
    ['@lsp.type.struct'] = 'Type',
    ['@lsp.type.type'] = 'Type',
    ['@lsp.type.typeParameter'] = 'Type',
    ['@lsp.type.variable'] = 'Identifier',
}

for group, target in pairs(links) do
    hi(group, { link = target })
end

hi('Bold', { bold = true })
hi('Italic', { italic = true })
hi('Strikethrough', { strikethrough = true })
